server:
  port: 8080

spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/as_easyleiloes
    username: tg
    password: secret
  flyway:
    locations: classpath:db/migration

logging:
  level:
    web: debug
    io:
      r2dbc:
        pool: debug
